import { MockKanbanService, ServiceError, STATUSES, STATUS_LABELS } from './service.js';
import { ApiService } from './api-service.js';

const params = new URLSearchParams(location.search);
const service = params.get('api') === '1' ? new ApiService(localStorage.getItem('tidyboard-api-url') || 'http://localhost:8000') : new MockKanbanService();
const $ = selector => document.querySelector(selector);
const state = { session: null, boards: [], board: null, tasks: [], draft: null, activeTab: 'active', query: '' };
let refreshing = false;
const esc = value => String(value ?? '').replace(/[&<>"']/g, c => ({ '&':'&amp;', '<':'&lt;', '>':'&gt;', '"':'&quot;', "'":'&#39;' }[c]));
const message = (text, kind = 'status') => { $('#message').textContent = text; $('#message').className = kind; };
const run = async (work, success = '') => { message('Saving…'); try { const result = await work(); if (success) message(success, 'success'); return result; } catch (error) { message(error.message, 'error'); return null; } };

async function refreshBoards() { state.boards = await service.listBoards(); renderBoards(); }
async function refreshVisible() { if (refreshing || !state.session || !state.board) return; refreshing = true; try { state.boards = await service.listBoards(); state.tasks = await service.listTasks(state.board.id); if (!state.draft) renderBoard(); else renderBoards(); } catch (error) { if (error.code === 'expired' || error.code === 'unauthenticated') message('Your session expired. Sign in again.', 'error'); } finally { refreshing = false; } }
async function openBoard(id) { await run(async () => { state.board = await service.openBoard(id); state.tasks = await service.listTasks(id); state.draft = null; await refreshBoards(); renderBoard(); }, 'Board opened.'); }
function renderBoards() { const list = state.boards.filter(board => state.activeTab === 'active' ? !board.archived : board.archived); $('#boards').innerHTML = list.length ? list.map(board => `<li><button class="board-link" data-board="${board.id}">${esc(board.name)} <small>${board.taskCount}</small></button><button class="archive" data-archive="${board.id}">${board.archived ? 'Restore' : 'Archive'}</button></li>`).join('') : '<li class="empty">No boards here yet.</li>'; $('#active-tab').ariaPressed = state.activeTab === 'active'; $('#archive-tab').ariaPressed = state.activeTab === 'archive'; }
function renderBoard() { const board = state.board; $('#board-title').textContent = board ? board.name : 'Choose a board'; $('#board').hidden = !board; if (!board) return; if (!$('#rename-board')) { const button = document.createElement('button'); button.id = 'rename-board'; button.className = 'secondary'; button.textContent = 'Rename'; $('#board-title').after(button); } $('#columns').innerHTML = STATUSES.map(status => `<section class="column" data-status="${status}"><h3>${STATUS_LABELS[status]}</h3>${state.tasks.filter(task => task.status === status).map(task => `<article class="task" draggable="true" data-task="${task.id}"><button class="task-open" data-task="${task.id}"><strong>${esc(task.title)}</strong><span>${esc(task.description)}</span></button></article>`).join('') || '<p class="empty">No tasks.</p>'}</section>`).join(''); }
function panel(task) { state.draft = { ...task }; if (!$('#conflict')) { const box = document.createElement('div'); box.id = 'conflict'; box.className = 'error'; box.hidden = true; $('#panel form').prepend(box); } $('#conflict').hidden = true; $('#save-task').disabled = false; $('#panel').showModal(); $('#task-title').value = task.title; $('#task-description').value = task.description; $('#task-status').value = task.status; $('#task-title').focus(); }
function closePanel() { if (state.draft && ($('#task-title').value !== state.draft.title || $('#task-description').value !== state.draft.description || $('#task-status').value !== state.draft.status) && !confirm('Discard unsaved changes?')) return; state.draft = null; $('#panel').close(); }
async function saveTask() { if (!state.draft) return; const input = { title: $('#task-title').value, description: $('#task-description').value, status: $('#task-status').value }; message('Saving…'); try { const task = await service.updateTask(state.board.id, state.draft.id, input, state.draft.version); message('Task saved.', 'success'); state.tasks = await service.listTasks(state.board.id); state.draft = null; $('#panel').close(); renderBoard(); } catch (error) { message(error.message, 'error'); if (error.code === 'conflict') { $('#conflict').hidden = false; $('#conflict').textContent = `Conflict. Latest saved title: “${error.latest.title}”. Your draft remains open for review.`; } if (error.code === 'unavailable') { $('#save-task').disabled = true; $('#conflict').hidden = false; $('#conflict').textContent = 'This task was deleted elsewhere. Copy your draft before closing; it cannot be recreated here.'; } } }
async function createTask() { const title = $('#new-task-title').value; const task = await run(() => service.createTask(state.board.id, title, $('#new-task-description').value), 'Task created.'); if (task) { $('#new-task-title').value = ''; $('#new-task-description').value = ''; state.tasks = await service.listTasks(state.board.id); renderBoard(); } }
async function deleteTask() { if (!state.draft || !confirm('Delete this task permanently?')) return; const result = await run(() => service.deleteTask(state.board.id, state.draft.id, state.draft.version), 'Task deleted.'); if (result) { state.tasks = await service.listTasks(state.board.id); closePanel(); renderBoard(); } }
async function moveTask(id, status) { const task = state.tasks.find(item => item.id === id); if (!task) return; const updated = await run(() => service.moveTask(state.board.id, id, status, task.version), 'Task moved.'); if (updated) { state.tasks = await service.listTasks(state.board.id); renderBoard(); } }
async function search() { const results = await run(() => service.search(state.query)); $('#results').innerHTML = state.query.trim() ? (results?.length ? results.map(task => `<li><button data-result="${task.boardId}" data-task-result="${task.id}">${esc(task.title)} — ${esc(task.boardName)} · ${STATUS_LABELS[task.status]}${task.archived ? ' · Archived' : ''}</button></li>`).join('') : '<li class="empty">No matching tasks.</li>') : '<li class="empty">Enter text to search titles and descriptions.</li>'; }
async function init() { state.session = await service.currentSession(); render(); }
function render() { const signedIn = Boolean(state.session); $('#signin').hidden = signedIn; $('#workspace').hidden = !signedIn; $('#sign-out').hidden = !signedIn; if (!signedIn) return; refreshBoards(); renderBoard(); }

document.addEventListener('click', async event => { const target = event.target.closest('button') || event.target; if (target.id === 'sign-in') { state.session = await service.signIn(); render(); message('Signed in with a development-only mock session.', 'success'); } if (target.id === 'sign-out') { await service.signOut(); state.session = null; state.board = null; render(); } if (target.id === 'active-tab' || target.id === 'archive-tab') { state.activeTab = target.id === 'active-tab' ? 'active' : 'archive'; renderBoards(); } if (target.dataset.board) openBoard(target.dataset.board); if (target.dataset.archive) { const board = state.boards.find(item => item.id === target.dataset.archive); await run(() => board.archived ? service.restoreBoard(board.id) : service.archiveBoard(board.id), board.archived ? 'Board restored.' : 'Board archived.'); if (state.board?.id === board.id) state.board = null; await refreshBoards(); renderBoard(); } if (target.dataset.task) panel(state.tasks.find(task => task.id === target.dataset.task)); if (target.dataset.result) { await openBoard(target.dataset.result); panel(state.tasks.find(task => task.id === target.dataset.taskResult)); } if (target.id === 'new-board') { const name = prompt('Board name'); if (name !== null) { const board = await run(() => service.createBoard(name), 'Board created.'); if (board) await openBoard(board.id); } } if (target.id === 'new-task') $('#new-task-title').focus(); if (target.id === 'close-panel' || target.id === 'cancel-task') closePanel(); if (target.id === 'save-task') saveTask(); if (target.id === 'delete-task') deleteTask(); if (target.id === 'create-task') createTask(); });
document.addEventListener('submit', event => { if (event.target.id === 'search-form') { event.preventDefault(); state.query = $('#search-input').value; search(); } });
document.addEventListener('dragstart', event => { if (event.target.dataset.task) event.dataTransfer.setData('text/plain', event.target.dataset.task); });
document.addEventListener('dragover', event => { if (event.target.closest('.column')) event.preventDefault(); });
document.addEventListener('drop', event => { const column = event.target.closest('.column'); if (column) { event.preventDefault(); moveTask(event.dataTransfer.getData('text/plain'), column.dataset.status); } });
init();
setInterval(refreshVisible, 3000);
document.addEventListener('click', async event => {
  if (event.target.id !== 'rename-board' || !state.board) return;
  const name = prompt('Board name', state.board.name);
  if (name === null) return;
  const board = await run(() => service.renameBoard(state.board.id, name), 'Board renamed.');
  if (board) { state.board = board; await refreshBoards(); renderBoard(); }
});
